### ISSUE TITLE
Cannot complete Part 1, task 2 in isolation

### ISSUE THREAD

**Issue by adamfortuna** [pluralsight-projects/Angular-AlbumStoreProductPage#21] opened 2017-10-06 14:44 UTC
From @carolinapowers 

> Carolina - When submiting one task at a time, task 2 of part 1, where you need to run `ng generate component product-description` will not pass after running the correct command and generating the correct files.

**Comment by jonfriskics** [comment] 2017-10-06 19:55
I can't reproduce this.  Here's the steps I took:

1. Fork + clone the project
2. Run the tests - the test `@product-description-component-created` fails.
3. In a Terminal in the Project's folder, type `ng generate component product-description`
4. Run the tests again - the test `@product-description-component-created` passes.

**Comment by jonfriskics** [comment] 2017-10-06 19:55
closing for now, but reopen if you're experiencing something else.

**Closed by jonfriskics** 2017-10-06 19:55 UTC
